import { Inter } from "next/font/google";
import SNG from "./components/SNG";
import "./style.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <div className="flexBox">
          <SNG />
          <div id="BODY">{children}</div>
        </div>
      </body>
    </html>
  );
}
